// @flow

export const APP_ERROR_CODE_UPDATE = 'APP_ERROR_CODE_UPDATE';
export const APP_NOTIFICATIONS_ADD = 'APP_NOTIFICATIONS_ADD';
export const APP_NOTIFICATIONS_REMOVE = 'APP_NOTIFICATIONS_REMOVE';

export const USER_IDENTITY_UPDATE = 'USER_IDENTITY_UPDATE';
export const USER_ACCOUNT_UPDATE = 'USER_ACCOUNT_UPDATE';
export const USER_TOKEN_UPDATE = 'USER_TOKEN_UPDATE';
export const USER_LIST_UPDATE = 'USER_LIST_UPDATE';
export const USER_DETAILS_UPDATE = 'USER_DETAILS_UPDATE';
export const LOGIN_FORM_UPDATE = 'LOGIN_FORM_UPDATE';
export const PASSWORD_RESET_REQUEST_FORM_UPDATE = 'PASSWORD_RESET_REQUEST_FORM_UPDATE';
export const PASSWORD_RESET_FORM_UPDATE = 'PASSWORD_RESET_FORM_UPDATE';
export const REGISTRATION_FORM_UPDATE = 'REGISTRATION_FORM_UPDATE';
export const PASSWORD_CHANGE_FORM_UPDATE = 'PASSWORD_CHANGE_FORM_UPDATE';
export const EMAIL_CHANGE_FORM_UPDATE = 'EMAIL_CHANGE_FORM_UPDATE';

export const BACKEND_USER_CREATION_FORM_UPDATE = 'BACKEND_USER_CREATION_FORM_UPDATE';
export const BACKEND_USER_UPDATING_FORM_UPDATE = 'BACKEND_USER_UPDATING_FORM_UPDATE';

export default {
  APP_ERROR_CODE_UPDATE,
  APP_NOTIFICATIONS_ADD,
  APP_NOTIFICATIONS_REMOVE,

  USER_IDENTITY_UPDATE,
  USER_ACCOUNT_UPDATE,
  USER_TOKEN_UPDATE,
  USER_LIST_UPDATE,
  USER_DETAILS_UPDATE,
  LOGIN_FORM_UPDATE,
  PASSWORD_RESET_REQUEST_FORM_UPDATE,
  PASSWORD_RESET_FORM_UPDATE,
  REGISTRATION_FORM_UPDATE,
  PASSWORD_CHANGE_FORM_UPDATE,
  EMAIL_CHANGE_FORM_UPDATE,

  BACKEND_USER_CREATION_FORM_UPDATE,
  BACKEND_USER_UPDATING_FORM_UPDATE,
};
